### PR TITLE
PEP8, refactor IEDB

### PR DESCRIPTION
**Pull request by iskandr**
- Using single instance of datacache.Cache instead of sprinkling hard-coded `subdir` arguments around multiple download points
- Split `iedb.py` into a sub-package called `iedb` with modules `mhc`, `tcell`, `alleles`. 
- Added a memoization to major functions in `iedb`
- Lots of misc. PEP8 fixes
- Got rid of `tcga` peptides functions, which used hackish MAF amino acid change parsing (can use Varcode in the future)

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/pepdata/36)

### CODE REVIEW

**Comment by arahuja** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pepdata/36)







---

<sup>**[pepdata/common.py, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhG84uB5Y8_VsiKss3)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/common.py#L38)):</sup>
Does it matter here if one of the two is hashable?

---

<sup>**[pepdata/hiv_frahm.py, line 31 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhGU_0B1u7lvI5aaXX)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/hiv_frahm.py#L31)):</sup>
Does `read_csv` work here or should it be `read_html`?

---

<sup>**[pepdata/iedb/alleles.py, line 86 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhH2HFivop8XrFMNsT)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/alleles.py#L86)):</sup>
Is this just debugging?

---

<sup>**[pepdata/iedb/common.py, line 35 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhHHHReJ-vsUs8xitE)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/common.py#L35)):</sup>
Is there a reason to do the aggregation individually and building a new dataframe instead of `df.agg({..})`?

---

<sup>**[pepdata/iedb/mhc.py, line 123 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhJq10Cc9-NiDQOd_b)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/mhc.py#L123)):</sup>
Can this be configurable?

---

<sup>**[pepdata/iedb/mhc.py, line 232 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhKWbbfwMn9Rb-lHeo)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/mhc.py#L232)):</sup>
quotes?

---

<sup>**[pepdata/iedb/mhc.py, line 235 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhKYFJgw-4f3mNElXq)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/mhc.py#L235)):</sup>
quotes?

---

<sup>**[pepdata/iedb/tcell.py, line 151 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhPPrMziHY55SIDo-U)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/tcell.py#L151)):</sup>
Can this just be a map on the series?
`mhc.map(lambda allele: 1 if ...)`

maybe no reason to change it.

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pepdata/36)







---

<sup>**[pepdata/common.py, line 38 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhG84uB5Y8_VsiKss3)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/common.py#L38)):</sup>
I was thinking of trying to handle that, do you think it's worth it? 

---

<sup>**[pepdata/hiv_frahm.py, line 31 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhGU_0B1u7lvI5aaXX)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/hiv_frahm.py#L31)):</sup>
This is an oddity of how I wrote datacache, it'll pull a table out of an HTML file by default and give you a CSV. I changed the filename to be "frahm.csv" and added an issue to datacache to not perform all that magic under the hood: https://github.com/hammerlab/datacache/issues/24

---

<sup>**[pepdata/iedb/alleles.py, line 86 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhH2HFivop8XrFMNsT)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/alleles.py#L86)):</sup>
Yep, getting rid of it

---

<sup>**[pepdata/iedb/common.py, line 35 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhHHHReJ-vsUs8xitE)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/common.py#L35)):</sup>
I guess the alternative is something like:

```
agg = groups.agg({'value' : np.mean, 'count' : lambda x: len(x), 'pos' : np.sum})
agg['neg'] = agg['count'] - agg['pos']
if min_count:
    mask = agg['counts'] >= min_count
    agg = agg[mask]
return agg
```

Would that work and do you think it's clearer?

---

<sup>**[pepdata/iedb/mhc.py, line 123 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhJq10Cc9-NiDQOd_b)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/mhc.py#L123)):</sup>
Added a `only_standard_amino_acids` option which defaults to True

---

<sup>**[pepdata/iedb/tcell.py, line 151 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhPPrMziHY55SIDo-U)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/tcell.py#L151)):</sup>
That logic is a bit too large to fit into a lambda, so I'd have to add an inline function, which I'm not sure makes the code any clearer. 

---

**Comment by arahuja** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pepdata/36)







---

<sup>**[pepdata/iedb/common.py, line 35 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhHHHReJ-vsUs8xitE)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/common.py#L35)):</sup>
Actually maybe I misunderstood what was going on here - was this getting averages and counts for many columns?  If so agg probably won't be clearer

it'd be `.agg({'col': [np.mean, np.sum'], 'col2': .. `

I guess its not clear what is in peptides so maybe a comment?

---

**Comment by iskandr** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/pepdata/36)







---

<sup>**[pepdata/iedb/common.py, line 35 \[r1\]](https://reviewable.io:443/reviews/hammerlab/pepdata/36#-JkhHHHReJ-vsUs8xitE)** ([raw file](https://github.com/hammerlab/pepdata/blob/df59876c75e9e63175e16a73c505143c5aab13e0/pepdata/iedb/common.py#L35)):</sup>
Added a docstring to hopefully clear up what this function actually does. 

---

**Pull request merged**
